apiVersion: v1
kind: Pod
metadata:
  name: ed-postgres
  labels:
    app: db
  namespace: betting-demo
spec:
  containers:
    - name: ed-postgres
      env:
        - name: POSTGRES_PASSWORD
          value: password
      image: 'quay.io/ccedgedemo/postgres:1.0'
      ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: svc-ed-postgres
  namespace: betting-demo
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Pod
metadata:
  name: ed-quarkus-backend
  labels:
    app: quarkus-app
  namespace: betting-demo  
spec:
  containers:
    - name: ed-quarkus-backend
      image: 'quay.io/ccedgedemo/quarkusapp:2.0.0'
      env:
      - name: KHOST
        value: my-cluster-kafka-bootstrap.betting-demo.svc:9092
      - name: DBHOST
        value: jdbc:postgresql://svc-ed-postgres.betting-demo.svc.cluster.local:5432/edgedemo
      - name: SECPROTO
        value: PLAINTEXT
      - name: KEYPATH
        value: /vol2/eternal-kafka.jks
      - name: KEYPASS
        value: password
      - name: PORT
        value: '8080'
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: svc-ed-quarkus-backend
  namespace: betting-demo
spec:
  selector:
    app: quarkus-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-ed-quarkus-backend
  namespace: betting-demo
  labels: {}
spec:
  to:
    kind: Service
    name: svc-ed-quarkus-backend
  tls: null
  port:
    targetPort: 8080
